### ISSUE TITLE
[Lesson 8] 중간에 종료 가능하게 만들기

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#10]
# [Lesson 8] 중간에 종료 가능하게 만들기

숫자 0을 입력하면 프로그램이 어떤 상황에 있든 종료하게 만들어야 한다. 사용자가 종료하기 위해 '0'을 입력하면 아래의 메세지를 표시하도록 하자.
 
```
Thank You 
``` 
 
- 제한사항
  - Thank You 를 표시한 뒤에는 프로그램을 종료 시킨다. 
  - git에서 'develop' branch로 분리하여 개발을 진행한다.

**Comment by bykauienm** [comment]
수정 완료했습니다~

**Comment by huinalam** [comment]
https://github.com/bykauienm/git_test/commit/0ff9abd0181e20347ee091c509fc85d52891ce6d

리뷰를 달아두었습니다. 피드백 부탁드립니다~

**Comment by bykauienm** [comment]
피드백에 대해 수정해 올렸습니다.

전에 branch가 분리되지 않아 이번에 분리하여 올렸습니다.

**Comment by huinalam** [comment]
![image](https://user-images.githubusercontent.com/4952867/35223549-183289a0-ffc5-11e7-9faa-ac0104d99e65.png)
여기서 Q를 누르고 enter를 치면 바로 종료되네요.
의도와 다르게 동작하는 것 같은데, 맞는지요?

**Comment by huinalam** [comment]
https://github.com/bykauienm/git_test/commit/0ff9abd0181e20347ee091c509fc85d52891ce6d#diff-1cfa84fcbecf5dec9fd6dd75466f7ddcR21

여기 메서드를 보고 있으면 의도가 모호한 것 같아요.
Normal로 하든 Emergency로 하든 똑같이 true로 리턴하고 있어서요.
어떤 의도로 쓰고 있는지 설명해주실 수 있겠어요?

**Comment by bykauienm** [comment]
1 >  별모양을 출력 후에 는 마지막에 종료 부분이라 Q와 0 둘다 눌러도 종료가 가능하게 했습니다.
의도와 맞게 동작하는 것은 맞는데 의미가 제대로 전달 안될 수 있겠네요 수정을 해야겠습니다.

2> 의도는 Normal이냐 Emergency냐에 따라 입력 받은 키값을 확인하고 종료하는 의도로 쓰고있습니다. 
Normal과 Emergency의 두가지 형태에 검사하기 위해 if 두개를 써서 두 타입에 대해 검사하고 true를 
리턴하고 있습니다.
하지만 의도가 제대로 전달되지 않는게 복잡하게 만들것 같습니다. 더 심플할게 수정해야겠습니다.

**Comment by bykauienm** [comment]
종료코드를 "0"하나로 통합하여 심플하게 수정하였습니다.

**Comment by huinalam** [comment]
수고하셨습니다.
해당 이슈는 종료합니다ㅎㅎ
