### ISSUE TITLE
[Lesson 5.5] 서로의 코드를 리뷰해주기

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#11]
# [Lesson 5.5] 서로의 코드를 리뷰해주기

같이 레슨 중인 분과 코드를 한번 리뷰해봅시다.
1. 다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
2. 다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.

**Comment by huinalam** [comment]
https://github.com/rbsejin/project1

위 주소는 같이 레슨 중인 세진님 소스코드입니다.

**Comment by rbsejin** [comment]
다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
1.1. 패턴을 문자열에 저장하여 한 번에 출력하는 것이 제가 생각하지 못한 부분이었습니다.
1.2. 행렬을 먼저 만들고, 행마다 *을 찍을지 공백을 찍을지를 선택하도록 한 부분이 인상적이었습니다.
1.3. StringBuilder 를 이용하여 실행 속도를 빠르게 한 것이 좋았습니다.
1.4. 출력,입력화면이 굉장히 깔끔해서 보기 좋았습니다.
1.5. 예시를 가로로 출력하니 훨씬 보기 좋았습니다.

다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.
2.1. 행렬을 만들고 *을 찍을지 말지를 선택하도록 패턴을 만든다면 새로운 패턴이 추가될 때 행,열과 *를 찍는 선택조건만 변경하면 쉽게 패턴을 추가할 수 있다고 생각됩니다.
2.2. 콘솔화면에서 출력된 문자를 없애는 법을 몰라서, 그리고 예시를 가로로 적을 생각을 못해서 계속 아래로 내려가는 방식으로 구현되었는데 이를 갈끔하게 수정해야겠다는 생각을 합니다.

**Comment by huinalam** [comment]
@bykauienm 세진님이 피드백 주셨는데... 윤배님도 세진님 코드에 대해 피드백 주면 좋겠네요^^

**Comment by rbsejin** [comment]
피드백 감사합니다. 제가 오늘 코드를 많이 고쳤습니다. 다시 한 번 피드백 가능할까요?

**Comment by huinalam** [comment]
서로 오프라인에서 리뷰(?)를 했으니 이 이슈는 마감합니다.
마지막 레슨 쯤에 다시 같이할 진행하는 이슈가 있으니 그때 다시 뵙죠 ^^
