### ISSUE TITLE
[Lesson 11] Pattern 추가 

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#14]
# [Lesson 11] Pattern 추가 

아래의 Pattern 을 추가한다.

```
*     *      *       
      **     **
             *** 
```

- 제한사항
  - 각 Pattern 간의 간격은 일정하도록 한다.  입력된 줄 + 2 줄 
  - 테스트코드를 작성한다.

**Comment by bykauienm** [comment]
수정 완료했습니다~

**Comment by huinalam** [comment]
깔끔하게 잘 됐네요^^
클로즈합니다~
