### ISSUE TITLE
[Leeson 12] Random Option 추가 

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#15]
# [Leeson 12] Random Option 추가 

Lesson 10 의 Pattern 에 반복의 숫자를 입력한 후, Random option 을 줄 수 있도록 한다. 혹은 새로운 Pattern 번호를 사용하여도 된다. 이 경우 하나의 선택이 추가되는 형태이다. 결과적으로 첫 번째는 Lesson 10 의 패턴을 선택 후 Random option 유무의 선택이 있는 형태이고, 두 번째의 방법은 새로운 선택을 주는 방식이다. 
 
Random 의 경우, Pattern 의 순서가 아래와 같이 바뀌어 나오게 된다.

```
* 
 
*
**
*** 
 
*
** 
 
*
**
***
**** 
```

- 제한사항
  - 동일한 숫자의 형태가 한번 이상 나와서는 서는 안됨.
  - 실행할 때마다 순서는 바뀌어서 표시되어야 함. 
  - 테스트코드를 작성한다.

**Comment by bykauienm** [comment]
수정 완료하였습니다

**Comment by huinalam** [comment]
잘 수정하셨어요!

미리 패턴을 결정해둔 후에, 10번 랜덤을 돌려서 swap하는 방식으로 랜덤을 구현한게 인상적이네요.

다만 랜덤이다보니 테스트코드를 구현함에 있어 고민이 많았던 것 같네요. 랜덤이다보니 어떤 상황일 때 테스트코드가 에러가 날지 모르니 1000000번 횟수로 테스트를 돌리는 방식으로 진행하셨어요. 괜찮은 방법이지만 여전히 모호한 점이 있어요. 1000001번째 에러가 나면 어쩌지? 라는 생각같은 거랄까요.

PrintTestRandomPyramid 테스트는 2가지를 테스트하고 있어요.
1. PatternRandomPyramid가 패턴을 잘 print했는지?
2. 랜덤으로 나온 형상을 잘 보였는지?

PatternRandomPyramid를 테스트하게 되면서 횟수로 갈 수 밖에 없는 이유는 '랜덤'에 있어요. '랜덤' 조차 테스트로 구현해야한닥도 생각하니 10000번 중에 한번이라도 틀리면 에러다- 라는 테스트 코드가 나오게 되죠. 잠시 생각해보죠. 랜덤을 굳이 테스트할 필요가 있을까요.

랜덤을 테스트할 필요가 없다면, PatternRandomPyramid클래스에 대한 구현을 다시 고민해볼 수 있을 것 같습니다. 랜덤 값과 print 구현을 분리하여 구현하는게 낫지 않을까? 아니면 구현된 랜덤 값을 볼 수 있는 property를 따로 만드는 것도 괜찮은 전략인 것 같구요.

한번 고민해보시구요~

**Comment by bykauienm** [comment]
수정 완료하였씁니다. print함수 내부를 분리해서 해봤습니다.

**Comment by huinalam** [comment]
좋습니다. 잘 마무리하셨네요.

다음 레슨이 마지막인데, 협동하는 부분이 남아있습니다. 아직 세진님을 조금 기다려야 하니, 기다릴 겸 약간의 수정요청을 할께요.

그간 긴 시간을 공들여온 소중한(?!) 별찍기 프로그램인데, ConsoleApp1나 UnitTestProject라는 프로젝트 이름이 좀 아쉬웠는데요. 이름을 바꿔보면 어떨까요? 이름은 마음에 드는걸로 지어보시면 좋겠어요-

참고로 프로젝트 이름을 바꾸시면, csproj을 수정하거나 소스 파일 경로와 네임스페이스를 조정해셔야 할겁니다.

**Comment by bykauienm** [comment]
수정 완료했습니다~

**Comment by huinalam** [comment]
git repository 이름도 바꿔볼까요? settings에 들어가면 이름을 변경할 수 있답니다.

**Comment by huinalam** [comment]
사실 좀 더 기다리는 입장에서^^... git repository를 약간 꾸며보도록 하죠.
`README.md`를 한번 작성해보시겠어요?
너무 복잡하거나 어렵게 적지 않으셔도 되구요. 간단한 코드 사용법 + 소스코드 galaxy 이름의 유래라던가 + 이 코드에 대한 간단한 설명 등등.. 너무 아무것도 없으니 밋밋하니 좀 꾸며본다고 생각하고 적어주시면 좋을 것 같습니다. (선택사항이에요.)

**Comment by bykauienm** [comment]
git repository 의 이름도 수정하고 README.md도 작성했습니다~

**Comment by huinalam** [comment]
토요일 오전부터 하시다니.. 부지런하시네요! ㅎㅎ
이 이슈는 닫습니다. 수고하셨어요!
