### ISSUE TITLE
[Collaborative Lesson 1] 사용자 입력 범위 변경

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#16]
# [Collaborative Lesson 1] 사용자 입력 범위 변경

Collaborative Lesson은 다른 레슨자의 코드를 수정하여 과제를 수행해야 한다.

1. 사용자가 입력할 수 있는 값인 1-100의 값을 1-50으로 수정한다.

- 제한사항
  - `master` 브랜치가 아닌 `dev` 브랜치에서 작업해야 한다.
  - 수정 후, 오류가 없어야 한다.

**Comment by huinalam** [comment]
@bykauienm 님, https://github.com/rbsejin/PatternDesign 에서 작업 완료 후, https://github.com/rbsejin/PatternDesign/issues/14 에 답글을 달아주면 됩니다.
질문이 있거나 완료가 되면, 서로 답변을 해주시면 됩니다.
완료 여부는 레포지토리 관리자가 해주시면 됩니다.
저는 서포트 역할로 조언하도록 할께요.

**Comment by rbsejin** [comment]
push가 안되는데요. 403 에러요 ㅠㅠ 이유가 뭔지 아시나요?

**Comment by rbsejin** [comment]
범위 수정하였습니다

**Comment by huinalam** [comment]
@bykauienm 잘 됐는지 확인해주시겠어요?

**Comment by bykauienm** [comment]
확인 했습니다. 잘 수정되었습니다~

**Comment by huinalam** [comment]
네 그럼 이 이슈는 마무리로...^^
