### ISSUE TITLE
[Collaborative Lesson 3] 마지막 패턴 추가

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#18]
# [Collaborative Lesson 3] 마지막 패턴 추가

Lesson 3 의 다이아몬드 Pattern 에 반복의 숫자를 입력한 후, Random option 을 줄 수 있도록 한다. 혹은 새로운 Pattern 번호를 사용하여도 된다. 이 경우 하나의 선택이 추가되는 형태이다. 결과적으로 첫 번째는 Lesson 3 의 패턴을 선택 후 Random option 유무의 선택이 있는 형태이고, 두 번째의 방법은 새로운 선택을 주는 방식이다. 
 
Random 의 경우, Pattern 의 순서가 아래와 같이 바뀌어 나오게 된다.

```
- Pattern 추가
   *

   *
  ***
 *****
  ***
   * 

   *
  ***
   *

   *
  ***
 *****
*******
 *****
  ***
   * 
```

- 제한사항
  - 다이아몬드 형태의 입력은 `홀수`만 입력되도록 한다.
  - 홀수만 출력이 되어야 한다.
  - 동일한 숫자의 형태가 한번 이상 나와서는 서는 안됨.
  - 실행할 때마다 순서는 바뀌어서 표시되어야 함. 
  - 테스트코드를 작성한다.
  - dev 브런치로 작성한다.
  - 코드 완료 후, pull request를 요청한다.

**Comment by huinalam** [comment]
@bykauienm @rbsejin 새로운 이슈 등록했어요.

**Comment by rbsejin** [comment]
윤배님이 프로그래밍을 너무 잘 만들어주셔서 금방 추가했네요.ㅎㅎ
단순히 다이아몬드 패턴을 반복하면 줄이 안맞는 문제 때문에
새로운 PrintDiamondGroup 라는 메소드를 생성하여 반복하였습니다.

**Comment by rbsejin** [comment]
아 그런데 지금 생각해보니 PatternDiamond 클래스를 상속받은 것이 이상한 것 같습니다. 수정하겠습니다

**Comment by rbsejin** [comment]
Base클래스를 상속받고, 홀수를 입력받기 위한 메소드를 추가하는 방식으로 수정하였습니다.

**Comment by bykauienm** [comment]
잘 추가 하셨네요.  Pull Request 요청도 부탁해요~

**Comment by huinalam** [comment]
사실 PR은 다음 레슨에서 있는건데^^... 먼저 이런 제안해주는 것.. 넘나 좋습니다...ㅎ

**Comment by rbsejin** [comment]
Pull Request 를 요청하는 것도 있었군요. ㅎㅎ 요청했습니다!

**Comment by bykauienm** [comment]
Pull Request 확인 후 완료했습니다~

**Comment by huinalam** [comment]
수고하셨습니다 ^^
