### ISSUE TITLE
[lesson0] 시작해볼까요?

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#2]
repository 이름이 좀 아쉽긴 하네요 ^^..

레슨을 시작해볼까요 :)

1. C# Console Application으로 프로젝트를 시작하여. 'hello world'를 출력하는 코드를 구현 후. push해주세요.
2. 'gitignore'이란 게 있습니다. 이를 공부해보시고, 이 프로젝트에 적용해주세요.
    - 완료 후 댓글로 간단한 설명도 달아주시구요.

**Comment by bykauienm** [comment]
1. > Hello World!를 출력하는 Console Application을 만들어 push 했습니다.
2. > .gitignore 파일에 commit시 제외할 항목을 등록하였습니다.
       제외할 목록은 프로젝트의 bin 폴더와 obj 폴더를 제외하였습니다.

**Comment by huinalam** [comment]
@bykauienm 

1. .gitignore이 어떤 용도로 사용하는지 간략하게 설명해주시겠어요?
2. .gitignore template를 찾아보시면 관련 정보가 많은데요. 이런게 왜 필요한걸까요? 그리고 그 template이 지금 적용된 gitignore과 어떤 차이점이 있는지 생각해보세요.

**Comment by bykauienm** [comment]
1> .gitignore 는 commit시에 제외 하고 싶은 파일이나 폴더 목록을 작성한 파일입니다.
위의 프로젝트에서의 bin, obj 같은 폴더는 굳이 repository에 올라갈 필요가 없어 제외한 것과 같습니다.
2.1> 사용자가 새롭게 환경을 구성하거나 변경 시 새롭게 .gitignore를 적용할 때 미리 작성해 놓은 template을 가져와 사용해 편의성과 새로 작성 중의 실수 예방을 방지하는데 도움이 될 수 있다고 생각합니다. c
2.2> 현재 적용된 template은 현재 repository에만 적용되어 있고, 그 대상도  ConsoleApp1 프로젝트만의 bin, obj 폴더에만 적용되어 다른 프로젝트의 파일이나 폴더에는 적용이 되지 않게 되어있습니다. 반면 찾아본 template들은 한가지 프로젝트에만이 아닌, 자바나 C++ 등 과 같은 해당 환경에 대한 전체적으로 적용되도록 작성되어 있었습니다.

**Comment by huinalam** [comment]
@bykauienm 

visual studio C# 관련 gitignore를 다시 한번 찾아보시면 좋을 것 같습니다. 각 언어 개발 환경에 따라 gitignore을 통해 제외하는 파일들이 모두 다르지요.

다시 한번 찾아보시고, 차이점이 있다면, 무슨 차이점인지 알려주시겠어요?

혹여 찾기어렵거나 이해가 되지 않는다면 답글을 주세요 :)

**Comment by bykauienm** [comment]
C#의 gitignore 파일에는 위에 올린것 처럼 폴더를 제외시키는 것 뿐만 아니라 *.zip과 같이 특정한 확장자를 가진 파일들을 제외 시키기도 합니다. 
그리고 ! 키워드를 이용해 제외되는 목록에서 무시할 파일들을 지정 했습니다.
[]를 사용해 [Dd]ebug 와 같이 대소문자에 구분 없이 적용되게 작성하기도 했습니다.

**Comment by huinalam** [comment]
@bykauienm 

계속되는 질문은 visual studio의 개발환경 상에서 git으로 commit시에 생략해도 되는 파일이 있다는 것을 알려주기 위함이었습니다 ^^...
visual studio gitignore 을 찾아보시면, ".vs" 폴더를 생략합니다. 아래에 있는 ".suo" 파일도 생략하구요.
그런데 확인해보시면 @bykauienm 님의 repository에는 .suo 파일이 남아있죠?
visual studio gitignore template에서는 이 폴더와 파일은 무엇이길래 생략하는 걸까요?

그 이유를 한번 고민해보고 답해주세요 :)

**Comment by bykauienm** [comment]
.vs 폴더는 프로젝트 관련 정보가 들어있는 폴더 입니다.  솔루션을 열때나 빌드 할때 생기며,  안에 db파일이나 .suo 파일 같은게 있었습니다. 그  .suo 파일은 솔루션의 사용자 옵션 정보가 들어있습니다.  .vs 폴더는 앞의 파일과 같이 개별적으로 적용되기에 다른 사람과 공유하거나 할 필요 없는 파일, 폴더들을 모아놓은 곳입니다.
 이런 파일들이나 폴더들은 각자 프로젝트 설정과 환경이 다르고, 또한 프로젝트를 열거나 빌드할 때 새로 생성되기 하기 때문에 해당 파일들을 다른 사람과 공유할 필요가 없기에 생략한다고 생각합니다.

**Comment by huinalam** [comment]
@bykauienm 
좋은 답변입니다 ^^
그럼 이제 기존의 git에 commit된 .vs 폴더를 없애야겠지요?

**Comment by bykauienm** [comment]
네, 기존 git의 commit된 .vs 폴더를 제거 했습니다.

**Comment by huinalam** [comment]
네, 이제 repository 보기가 좋네요^^
해당 이슈는 close 하겠습니다.
수고하셨습니다 :)
