### ISSUE TITLE
[Final Lesson] Pull Request & Code Review

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#20]
# [Final Lesson] Pull Request & Code Review

1. 다른 개발자가 자신의 프로젝트에 요청한 pull request를 보고 코드리뷰 후 merge를 수행한다.

- 힌트
  - 다른 개발자의 repository에서 코드리뷰를 해주면 된다.

**Comment by huinalam** [comment]
코드 리뷰는 내일 오후 7시에 오프라인에서 진행합니다 ^^
PR까지 부탁할께요.

**Comment by bykauienm** [comment]
@huinalam 레슨, 오래 걸리긴 했지만 드디어 끝났네요. 레슨 하면서 재밌고 도움도 많이 되었습니다. Git, TestCode 같은 것들은 이번에 알게됬는데 사용해 보면서 유용함이나 필요성에 대해 느껴지고 더 알아보고 싶은 욕구도 생기고 좋았습니다. 
 개발이 단순히 코드만 작성하는 것 뿐만 아니라 관리, 협업, 테스트 등 다양한 면에서 생각해야 한다는걸 느낄 수 있었어요. 이런건 학교에서 가르쳐주거나 하진 않았고, 혼자 공부 했을 대도 접해보지 못했었거든요.  
 때때로 어떤 공부를 할지, 어떻게 공부를 할지 방향을 잡는데 막연하거나 고민 될때 많은 도움이 될 것 같아요, 좋은 레슨 감사합니다. 수고하셨습니다!

@rbsejin 같이 레슨 잘 끝내서 다행이에요, 처음에 어려워 하시던데, 그래도 잘 배우면서 해나가시더라구요. 저도 그렇지만 아직 배울게 많잖아요. 넘 압박받지 마시고,  맘 편하게 먹고 해도 괜찮을거에요.
 열정적으로 하는 모습 보니 앞으로 더 잘 하게 될거라 생각해요. 새롭게 만나서 반갑고 같이 하면서 재밌었어요. 앞으로도 홧팅!

Final Lesson 클로즈^^/

**Comment by huinalam** [comment]
@bykauienm 님.

회사일과 레슨을 병행하는게 쉽지 않은데, 잘 따라와주셔서 고마워요. 회사일 끝나고 새벽에 서로 푸시하고 이슈달던 일이 이젠 즐거운 추억(?!)으로 남게 되었네요ㅎㅎ

레슨을 진행하면서 느낀 점이 있는데, 큰 흔들림 없이 우직하게 나아가는 모습이 윤배님의 장점이 아닌가 싶었어요. 레슨 진행 중에도 큰 혼란이나 이슈없이 잘 마무리될 수 있었던 건 윤배님의 그 장점이 잘 살려졌기 때문이 아닌가 싶어요.

이 레슨을 시작으로 앞으로 서로 협업해야할 일이 많아질거에요. 그러면 서로 부딪힐 점도 많아지겠죠^^.. 같이 잘 헤쳐나가봐요. 잘 부탁드립니다 :)
