### ISSUE TITLE
[Lesson1] 첫 Pattern

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#3]
아래와 같이 표시되도록 코드를 작성해보세요.
 
```
* 
**
***
****
***** 
```

**Comment by bykauienm** [comment]
pattern_1st 프로젝트에 코드 작성한 후 올렸습니다.

**Comment by huinalam** [comment]
하하 이건 제가 의도를 잘못 전달했군요..
기존 코드에서 위와 같이 표현할 수 있도록 코드를 구현 후 커밋해주시면 됩니다.
Pattern_1st 삭제 후, 'ConsoleApp1' 프로젝트에서 시작해주세요.

**Comment by bykauienm** [comment]
Pattern_1st 삭제 완료 후 ConsoleApp1 프로젝트에 다시 작성하였습니다.

**Comment by huinalam** [comment]
잘하셨습니다.
레슨1을 마치고 레슨2로 가도록 할께요 :)
