### ISSUE TITLE
[Lesson2] 사용자가 입력가능하도록 만든다.

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#4]
Lesson 1의 프로젝트를 수정하여 사용자가 몇 줄을 찍을 것인지 할 수 있도록 한다. 

``` 
How many lines? (1..100)  7
*
**
***
****
*****
******
******* 
```

- 제한조건
  - 사용자는 1 부터 100 까지의 값을 칠 수 있다. 
  - 사용자가 0 이나 마이너스 값을 치는 경우에는 아래와 같이 표시하고 input 을 다시 요구한다. 100 보다 큰 경우에도 마찬가지이다.
  - 사용자가 정상 값을 칠 때까지 계속 입력을 받는다.
  - 정상적으로 입력하면, 화면에 표시하고 종료한다. 
 
```
Invalid input – Range 1..100
How many lines? (1..100) 
```

**Comment by bykauienm** [comment]
수정 완료하였습니다.

**Comment by huinalam** [comment]
잘하셨어요.

약간의 팁을 드리자면, String 연산시 StringBuilder를 사용하면 성능상 이점이 있습니다.

String 연산하는 부분을 StringBuilder로 수정해보시겠어요?
그리고 String과 StringBuilder의 간단하게 차이를 설명해주세요.

**Comment by bykauienm** [comment]
> StringBuilder로 수정 완료하였습니다.
> string은 메모리에 할당된 후 변경 할 수 없기 때문에 연산하거나 할 때 새롭게 인스턴스로 생성됩니다. 그에 비해 StringBuilder는 새로 인스턴스를 생성하지 않고 내부 메모리에서 수정, 삭제 등의 연산을 하기 때문에 많고 반복적인 문자열 처리에 StringBuilder가 성능상 이점이 있습니다.

**Comment by huinalam** [comment]
네 좋습니다 :)
해당 레슨을 마무리하죠.
