### ISSUE TITLE
[Lesson 3] 새로운 Pattern

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#5]
아래의 2 가지 Pattern 을 추가하고 (총 3 개의 Pattern 이 된다)
사용자가 원하는 Pattern 을 선택할 수 있도록 한다. 

```
- Pattern 추가
*****
 ****
  ***
   **
    * 
 
- Pattern 추가
   *
  ***
 *****
  ***
   * 
```

- 제한사항
  - 잘못된 Input 이 들어오면 다시 입력을 받도록 한다.
  - Input 입력방법은 정해져 있지 않다.
  - 사용자가 이해하기 쉬운 것을 제안하라.
  - 다이아몬드 형태의 입력은 홀수만 입력되도록 한다.
  - 정상적으로 선택한 후 종료한다.

**Comment by bykauienm** [comment]
수정 완료 하였습니다.

**Comment by huinalam** [comment]
아래에 코드 리뷰를 해두었습니다.
[코드 리뷰](https://github.com/bykauienm/git_test/commit/55fc51f05fb1e79e35430cc8d7c6b9e742788732)

코드 작성시, 아래 코드 가이드를 참고하면 좋을 것 같습니다.
[코딩 가이드](http://www.csharpstudy.com/Guide/Coding-guide.aspx)

확인 후 피드백주세요 :)

**Comment by bykauienm** [comment]
감사합니다~ 코드는 수정해서 다시 올렸습니다.

**Comment by huinalam** [comment]
@bykauienm 
코맨트를 더 추가했습니다.
https://github.com/bykauienm/git_test/commit/55fc51f05fb1e79e35430cc8d7c6b9e742788732#r25920402
https://github.com/bykauienm/git_test/commit/55fc51f05fb1e79e35430cc8d7c6b9e742788732#r25920419

확인 부탁드릴께요.

**Comment by bykauienm** [comment]
넵 확인 후 다시 수정했습니다.

**Comment by huinalam** [comment]
@bykauienm 
수고하셨습니다.
이전보다 코드가 훨씬 깔끔해지고 보기가 좋네요^^

추가적인 조언을 드리자면.. 다음부터는 커밋 내용을 최대한 나누어 적어, 어떤 사항을 수정했는지 내용을 남기면 좋겠습니다.
가령
'if, for문시 중괄호를 넣어 일관성 있게 수정'
'a,b,c,i,j 이름 리팩토링'
이렇게 나눠서 커밋하면, 이 코드를 수정했을 때 어떤 이유로 수정했는지 기록에 남길 수 있거든요.

그럼 해당 이슈를 마무리하겠습니다.
