### ISSUE TITLE
[Lesson 4] 무한 Loop 및 Pattern 추가 

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#6]
한번 하고 종료되지 않고, 계속 Loop 를 돌도록 만든다.
아울러, 아래의 Pattern 을 추가한다. 
 
```
- Pattern 추가
   ***
  ***
 *** 
 
- Pattern 추가
   ***
  **
 * 
```

**Comment by bykauienm** [comment]
수정 완료 하였습니다.

**Comment by huinalam** [comment]
커밋 단위를 더 쪼갤 수 있었으면 좋겠습니다.
가령
- 패턴 A 추가
- 패턴 B 추가
- 종료 기능 적용
이런 씩으로요.
그래야 나중에 커밋 로그를 보고서 어떤 사항이 수정되었는지 확인하기 쉽고, 코드 리뷰시 어떤 코드만 중점적으로 보면 될지 이해하기 쉽기 때문입니다.

잘 적용되었네요. 수고하셨습니다 :)

**Comment by bykauienm** [comment]
네 감사합니다~ 다음 커밋때 해보겠습니다
