### ISSUE TITLE
[Lesson 5] Source File 리팩토링

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#7]
# [Lesson 5] Source File 리팩토링

이전처럼 앞으로도 요구사항에 따라 코드가 계속 수정될 예정이다.
어떻게 프로젝트 구조를 설계하면, 기존 코드를 많이 변경하지 않으면서도 새로운 기능을 큰 변경없이 쉽게 넣을 수 있을지, 고민해보고 변경해보라.

- 힌트
  - interface나 abstract를 활용한다.
- 도전과제
  - 디자인 패턴을 찾아 응용해보아도 좋다.

**Comment by bykauienm** [comment]
코드 변경 하였습니다

**Comment by huinalam** [comment]
Dictionary를 활용한 방법.. 좋네요 ^^
잘하셨습니다.

이건 질문인데요.
RequestInputTypeMessage()
메서드에 각 별모양이 들어가있잖아요?
추후에 별이 추가되거나 수정하면 고치기가 까다로울 것 같은데,
염두해두신 생각이 있으신지요?

**Comment by bykauienm** [comment]
그 땐 각 패턴별로 일부 출력된 별모양을 다시 합해 출력해 주는 방식 등으로 새로 클래스나 메서드를 추가하겠씁니다.

**Comment by huinalam** [comment]
다음 번에 어떻게 구현하실지 기대되네요 ^^
간단한 코드리뷰만 남겨두었습니다. 큰 이슈는 아니니, 다음 레슨을 진행하면서 진행하면 될 것 같습니다.

그럼 이 이슈는 닫겠습니다.
