### ISSUE TITLE
[Lesson 6] Library로 만들기

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#8]
# [Lesson 6] Library로 만들기

메인부분을 제외한 입력부분과 수행부분을 라이브러리로 만들고, 메인 프로젝트가 라이브러리를 reference로 참조하여 사용하게 만든다. 라이브러리 이름은 스스로 정한다.

**Comment by bykauienm** [comment]
수정 완료하였습니다.

**Comment by huinalam** [comment]
잘하셨습니다 ^^..

1.
아쉽게도 ConsoleApp1에 실행파일(bin, obj, dll) 등이 있네요.
build로 나온 결과물은 코드 관리 대상이 아닙니다. 이를 gitignore을 통해 생략해주세요.

2.
솔루션 파일(sln)이 2개나 있네요.
이를 1개로 하고, 서로 참조할 수 있도록 프로젝트 구조를 만들어 주시겠어요?

3.
dll 참조가 아닌, 프로젝트 내에서 project reference로 참조해주세요.

**Comment by bykauienm** [comment]
수정 완료했습니다~

**Comment by huinalam** [comment]
하나만 더..^^

sln 파일은 root에 놓아두는 게 좋겠죠?
ConsoleApp1 안에 있으니 솔루션 디렉토리 구조가 헤깔릴 수 있으니까요.
sln 파일을 README.md가 있는 디렉토리로 위치를 변경해주세요.

**Comment by bykauienm** [comment]
위치 변경했습니다~

**Comment by huinalam** [comment]
점점 디렉토리 구조가 보기 좋아지네요^^
수고하셨습니다 :)
