### ISSUE TITLE
[Lesson 7] Test Code 구현하기

### ISSUE THREAD

**Issue by huinalam** [bykauienm/git_test#9]
# [Lesson 7] Test Code 구현하기

기존 프로그램의 '입력부분', '수행부분'에 대한 테스트 코드를 구현한다.

- 제한사항
  - MSTest 기반으로 작성한다. (기호에 따라 XUnit등을 활용해도 좋다)
  - 테스트코드는 AAA패턴으로 구현한다.
  - 이후 모든 코드는 테스트 코드를 작성할 수 있도록 구현한다.

- 힌트
  - 테스트 코드는 정상적인 동작 방식을 보장, 프로그램의 점진적 설계, 다른 사람이 코드를 사용하고자 할 때 구현의 의도를 알리려는 목적으로 작성이 된다.

- 힌트 코드
```
[TestMethod]
public void CreateStar() 
{
  // Arrange
  var validResult = "* ** ***";
  var parttern = new StarParttern();
  
  // Act
  var result = parttern.Build(5);

  // Assert
  Assert.Equal(validResult, result)
}
```

**Comment by bykauienm** [comment]
수정 완료하였습니다.~ 테스트 코드 구현이 익숙하지 않아 제대로 한건지 모르겠네요

**Comment by huinalam** [comment]
1. 와우! 잘 이해하시고 잘 만드셨네요! 코드 보는 저도 기분이 좋네요.
전 테스트코드는 짜면서 많이 고민하는게 네이밍인데요. 어떤 분들은 테스트 메서드를 한글로 적기도 하는데, 나쁘지 않은 방법 같더라구요. (오픈소스가 아닌 이상에 말이죠)
1,2,3,4,5 라는 네이밍이 조금 애매한데 한번 고민해보시고 다른 방법이 있는지, 아니면 이렇게 네이밍하는게 낫을지 고민해보시고 답을 주시겠어요?

2. 테스트 코드 구현시 AAA패턴 방식으로 잘 씁니다. 이 패턴에 대해서 간략하게 설명해주시겠어요?

**Comment by bykauienm** [comment]
1. 1,2,3,4,5라는 네이밍은 어떤 패턴에 대한 테스트인지 확인하기 어렵게 작성한것 같습니다. 
여기선 패턴의 특징을 나타내는 이름을 사용해 네이밍을 하는게 더 적당하지 않을까 생각듭니다.
다시 패턴 이름을 사용해 수정해보겠습니다~

2. AAA 패턴은 테스트 코드를 작성 할 때 세 부분으로 나눠서 작성합니다.
Arrange, Act, Assert로
Arrange에서는 테스트에 사용할 변수나 객체 등을 생성, 준비하고
Act에서는 테스트를 실행합니다
Assert에서는 테스트가 통과되는 조건을 작성해 테스트가 제대로 되는지 확인합니다.

**Comment by huinalam** [comment]
1. 아무래도 테스트를 돌리게 되면, 실패시 실패한 함수명이 나오게되는데, 그게 숫자만 적혀있으면 무엇이 잘못되었는지 바로 알기가 쉽지 않을 것 같네요. 수정 부탁드리겠습니다 :)

**Comment by bykauienm** [comment]
1. 네, 저번에 커밋 하면서 테스트코드 함수 이름에 숫자를 빼고 패턴 이름으로 바꿔놓았습니다~

**Comment by huinalam** [comment]
깔끔하게 잘 작성하셨네요.
점점 성장하시는 것 같아 기분이 좋습니다^^

간단한 수정요청을 하나 할께요.
`PatternPrinter`클래스 테스트와 `PatternBase` 클래스 테스트 파일을 구분하면 어떨까요?
테스트 파일도 클래스 분류별로 나눠서 괄리하면 보기에 편한 이점이 있어서요.

**Comment by bykauienm** [comment]
수정 완료했습니다~

**Comment by huinalam** [comment]
네 수고하셨습니다 ^^ 해당 이슈는 클로즈 할께요.
